# After changing this file, check it on:
#   http://lint.travis-ci.org/
#

dist: trusty
sudo: required
language: python
matrix:
  fast_finish: true
  include:
  - python: 2.7
    env:
    - PYTHON=2.7
  - python: 2.7
    env:
    - PYTHON=3.3
  - python: 2.7
    env:
    - PYTHON=3.4
  - python: 2.7
    env:
    - PYTHON=3.5
  - python: 2.7
    env:
    - PYTHON=3.6
# Setup anaconda
before_install:
  - sudo apt update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  - DEPS="numpy scipy pip nose pytest pandas=0.19 statsmodels=0.8.0"
  - conda create -q -n test-environment python=$PYTHON $DEPS
  - source activate test-environment
  - python setup.py install
script:
  - pytest
